spring:
  application:
    name: spring-integration-test-poc
  datasource:
    url: jdbc:h2:mem:dogsdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect